// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for windows - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBeaS10kqIHZMRzuFxpiTTwa9OmCCxe0FM",
    appId: "1:32719981642:web:a45ce0aa269a9d0018aab3",
    messagingSenderId: "32719981642",
    projectId: "cmsc23-project-69d2f",
    authDomain: "cmsc23-project-69d2f.firebaseapp.com",
    storageBucket: "cmsc23-project-69d2f.appspot.com",
    measurementId: "G-TWD6V9LGLB",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAOYFOxikUBko7KWW2PP0aZeYtuGmbTFrs",
    appId: "1:32719981642:android:10225e90d92500ea18aab3",
    messagingSenderId: "32719981642",
    projectId: "cmsc23-project-69d2f",
    storageBucket: "cmsc23-project-69d2f.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDDmd_45WODU0LiI8Qs5iqMn4sptOguQ64",
    appId: "1:32719981642:ios:b60443b0617d3a6118aab3",
    messagingSenderId: "32719981642",
    projectId: "cmsc23-project-69d2f",
    storageBucket: "cmsc23-project-69d2f.appspot.com",
    iosClientId:
        "32719981642-jkqughdseceov4i8fikoqpr4mr33k07f.apps.googleusercontent.com",
    iosBundleId: "com.example.sharedTodoApp",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDDmd_45WODU0LiI8Qs5iqMn4sptOguQ64",
    appId: "1:32719981642:ios:b60443b0617d3a6118aab3",
    messagingSenderId: "32719981642",
    projectId: "cmsc23-project-69d2f",
    storageBucket: "cmsc23-project-69d2f.appspot.com",
    iosClientId:
        "32719981642-jkqughdseceov4i8fikoqpr4mr33k07f.apps.googleusercontent.com",
    iosBundleId: "com.example.sharedTodoApp",
  );
}
